# Test how well document scales back to original...
gpu
lazy
debugfont off
clearperf
label start
printperf
clear
debug Add rabbit 1
loadsvg svg-tests/rabbit_simple.svg
loop 250 pxzoom 508 305 1
debug Add rabbit 2
loadsvg svg-tests/rabbit_simple.svg
loop 250 pxzoom 508 305 1
debug Add rabbit 3
loadsvg svg-tests/rabbit_simple.svg
loop 500 pxzoom 508 305 -1
loop 500 pxzoom 508 305 1
debug Repeat
goto start
wait
